### ISSUE TITLE
[GET] Fetch all books to display

### ISSUE THREAD

**Issue by nhtoby311** [vantoan19/InfinityLibrary#14]
- [GET]
- Fetch all books to display on main screen
- Change params in query to apply different filters `..?filter=...` 
- Should return array of object type Book. Find it in [wiki](https://github.com/vantoan19/InfinityLibrary/wiki#server-return-types-from-backend-to-frontend)
- On default, should return the "Recommended" filter option. Like on the design: 
![image](https://user-images.githubusercontent.com/52330522/201677304-6c6379ef-b1df-4a5a-94f8-8a172ad9f904.png)

**Comment by nhtoby311** [comment]
Update the type!

**Comment by amigo1121** [comment]
what's the type of filter?

**Comment by amigo1121** [comment]
I suggest the parameter should be `sort` instead of `filter`, some values could be `sort=default`, `sort=time,asc`, `sort=time,desc`

**Comment by nhtoby311** [comment]
> I suggest the parameter should be sort instead of filter, some values could be sort=default, sort=time,asc, sort=time,desc

I'm okay with using sort. However, for time, could it be `sort=time-asc`, because on frontend, that should be a `string` to pass in the parameter.

**Comment by amigo1121** [comment]
Done!
