### ISSUE TITLE
[GET] Get details data of a Book

### ISSUE THREAD

**Issue by nhtoby311** [vantoan19/InfinityLibrary#15]
- [GET]
- Fetch a specific data of a Book.
- Change params in query to apply different book_id `..?book_id=...` 
- Should return an object type BookDetails. Find it in [wiki](https://github.com/vantoan19/InfinityLibrary/wiki#server-return-types-from-backend-to-frontend)
- Use for this design:
![image](https://user-images.githubusercontent.com/52330522/201678167-5e5fcb62-a7fb-4e26-b430-fc6f475279e7.png)

**Comment by nhtoby311** [comment]
Update the type! Possible having another API to call fetch user based on `user_id` What do you think?

**Comment by amigo1121** [comment]
Yeah, it should be. I will return the user_id of the book so you can use it to get the user data.

**Comment by amigo1121** [comment]
Done!
